work_dir: ./work_dir/recognition/ntu-xsub/ST_VAE
seed: 02130511

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ntu120/xset/train_data_joint.npy
  label_path: ./data/ntu120/xset/train_label.pkl
test_feeder_args:
  data_path: ./data/ntu120/xset/val_data_joint.npy
  label_path: ./data/ntu120/xset/val_label.pkl

# model
model: net.CVAE_lstm.CVAE
model_args:
  in_channels: 75
  T: 300
  n_z: 32
  num_class: 120
  

#optim
optimizer: "Adam"
nesterov: "True"
weight_decay: 0.0001
base_lr: 0.1
step: [40,60,70]

# training
device: [0]
batch_size: 32
test_batch_size: 32
num_epoch: 80



