
# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
  data_path: ./data/ntu120/ntu20/xset/val_data_joint.npy
  label_path: ./data/ntu120/ntu20/xset/val_label.pkl

# model
model: net.ST_AAE.ST_AAE
model_args:
  in_channels: 3
  T: 300
  V: 25
  M: 2
  num_class: 20
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# test 
phase: test
device: 0
test_batch_size: 64

