work_dir: ./work_dir/recognition/ntu-xview/ST_VAE
seed: 02130511

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ntu120/ntu20/xset/train_data_joint.npy
  label_path: ./data/ntu120/ntu20/xset/train_label.pkl
test_feeder_args:
  data_path: ./data/ntu120/ntu20/xset/val_data_joint.npy
  label_path: ./data/ntu120/ntu20/xset/val_label.pkl

# model
model: net.ST_AAE.ST_AAE
model_args:
  in_channels: 3
  T: 300
  V: 25
  M: 2
  num_class: 20
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'


#optim
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]

# training
device: [0]
batch_size: 64
test_batch_size: 64
num_epoch: 80



