# command line: bla.py

base_lr: 0.1
batch_size: 1
config: C:\Personal\Sourecode\school\year3\FYP\GCN-AAE\config\ntu120-xsub\train.yaml
debug: false
device:
- 0
eval_interval: 5
feeder: feeders.feeder.Feeder
ignore_weights: []
log_interval: 100
model: net.CVAE_stgcn.CVAE
model_args:
    T: 300
    V: 25
    dropout: 0.5
    edge_importance_weighting: true
    graph_args:
        layout: ntu-rgb+d
        strategy: spatial
    in_channels: 3
    n_z: 32
nesterov: true
num_epoch: 80
num_worker: 4
optimizer: SGD
pavi_log: false
phase: train
print_log: true
save_interval: 10
save_log: true
save_result: false
show_topk:
- 1
- 5
start_epoch: 0
step:
- 10
- 50
test_batch_size: 1
test_feeder_args:
    data_path: ./data/ntu120/xsub/val_data_joint.npy
    label_path: ./data/ntu120/xsub/val_label.pkl
train_feeder_args:
    data_path: ./data/ntu120/xsub/train_data_joint.npy
    label_path: ./data/ntu120/xsub/train_label.pkl
use_gpu: true
weight_decay: 0.0001
weights: null
work_dir: ./work_dir/recognition/ntu-xsub/ST_GCN
