weights: ./models/st_gcn.ntu-xsub.pt

# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ntu120/xsub/val_data_joint.npy
  label_path: ./data/ntu120/xsub/val_label.pkl

# model
model: net.CVAE_stgcn.CVAE
model_args:
  in_channels: 3
  num_class: 60
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# test 
phase: test
device: 0
test_batch_size: 64

