work_dir: ./work_dir/recognition/ntu-xsub/ST_VAE

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ntu120/xsub/train_data_joint.npy
  label_path: ./data/ntu120/xsub/train_label.pkl
test_feeder_args:
  data_path: ./data/ntu120/xsub/val_data_joint.npy
  label_path: ./data/ntu120/xsub/val_label.pkl

# model
model: net.CVAE_stgcn.CVAE
model_args:
  in_channels: 3
  T: 300
  V: 25
  n_z: 32
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

#optim
optimizer: "SGD"
nesterov: "True"
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]

# training
device: [0]
batch_size: 1
test_batch_size: 1
num_epoch: 80



